ALTER TABLE student_health
    ADD COLUMN IF NOT EXISTS has_respiratory_condition  BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS has_orthopedic_condition   BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS had_surgery                BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS surgery_description        TEXT,
    ADD COLUMN IF NOT EXISTS has_chronic_pain           BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS chronic_pain_location      VARCHAR(200),
    ADD COLUMN IF NOT EXISTS smokes                     BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS drinks_alcohol             BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS alcohol_frequency          VARCHAR(30),
    ADD COLUMN IF NOT EXISTS sleep_hours                INTEGER,
    ADD COLUMN IF NOT EXISTS stress_level               INTEGER,
    ADD COLUMN IF NOT EXISTS activity_level             VARCHAR(30),
    ADD COLUMN IF NOT EXISTS fitness_goal               VARCHAR(50),
    ADD COLUMN IF NOT EXISTS fitness_level              VARCHAR(20),
    ADD COLUMN IF NOT EXISTS exercise_history           TEXT,
    ADD COLUMN IF NOT EXISTS parq_heart_problem         BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS parq_chest_pain_exercise   BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS parq_chest_pain_rest       BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS parq_dizziness             BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS parq_bone_joint            BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS parq_blood_pressure_meds   BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS parq_other_reason          BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS parq_other_reason_detail   TEXT;
